# Generated by Django 5.0.4 on 2024-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collecte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturedata',
            old_name='sensor',
            new_name='sensor_id',
        ),
    ]
