# Generated by Django 5.0.4 on 2024-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collecte', '0002_rename_sensor_temperaturedata_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
