# Generated by Django 5.0.4 on 2024-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collecte', '0003_alter_temperaturedata_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='emplacement',
        ),
        migrations.AlterField(
            model_name='temperaturedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
